db_layer::RolType
def db_layer.RolType.getValue
Referenced by db_layer.RolType.get_adm_user, db_layer.RolType.get_adv_user, db_layer.RolType.get_kid_user, db_layer.RolType.get_guest_user.
def db_layer.RolType.getKeys
def db_layer.RolType.getValues
Referenced by db_layer.RolType.dbTypes.
def db_layer.RolType.dbTypes
References db_layer.RolType.getValues.
def db_layer.RolType.get_adm_user_key
def db_layer.RolType.get_adv_user_key
def db_layer.RolType.get_kid_user_key
def db_layer.RolType.get_guest_user_key
def db_layer.RolType.get_adm_user
References db_layer.RolType.getValue.
def db_layer.RolType.get_adv_user
References db_layer.RolType.getValue.
def db_layer.RolType.get_kid_user
References db_layer.RolType.getValue.
def db_layer.RolType.get_guest_user
References db_layer.RolType.getValue.