Proxy::Proxy
tuple Proxy.Proxy::theDB
Proxy.Proxy::threadServer
string Proxy.Proxy::server_version
Referenced by Proxy.Proxy.int_HEAD_PROXY_AUTH, Proxy.Proxy.int_HEAD_HTTP_AUTH.
string Proxy.Proxy::proxy_user
Referenced by Proxy.Proxy.do_CONNECT.
string Proxy.Proxy::proxy_password
string Proxy.Proxy::http_user
string Proxy.Proxy::http_password
Proxy.Proxy::bodySize
Referenced by Proxy.Proxy.svc_hndl_LIB, Proxy.Proxy.svc_hndl_ULIB, Proxy.Proxy.int_send_HEADERS_JSON, Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_send_HEADERS_FILETYPE.
int Proxy.Proxy::Allowed
Referenced by Proxy.Proxy.BASIC, Proxy.Proxy.do_CONNECT.
string Proxy.Proxy::parsed_path
Referenced by Proxy.Proxy.do_CONNECT.
string Proxy.Proxy::content
Referenced by Proxy.Proxy.BASIC.
int Proxy.Proxy::content_lenght
Referenced by Proxy.Proxy.svc_hndl_LIB, Proxy.Proxy.svc_hndl_ULIB, Proxy.Proxy.int_send_HEADERS_JSON, Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.BASIC, Proxy.Proxy.do_CONNECT.
list Proxy.Proxy::processed_headers
Referenced by Proxy.Proxy.BASIC.
int Proxy.Proxy::code
Referenced by Proxy.Proxy.svc_hndl_LIB, Proxy.Proxy.svc_hndl_ULIB, Proxy.Proxy.int_send_HEADERS_JSON, Proxy.Proxy.int_send_HEADERS_redirect, Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_send_HEADERS_FILETYPE, Proxy.Proxy.int_HEAD_PROXY_AUTH, Proxy.Proxy.int_HEAD_HTTP_AUTH, Proxy.Proxy.BASIC, Proxy.Proxy.do_CONNECT.
Proxy.Proxy::content_cached
Referenced by Proxy.Proxy.BASIC.
tuple Proxy.Proxy::myServerAddress
tuple Proxy.Proxy::logger
dictionary Proxy.Proxy::LocalServices
dictionary Proxy.Proxy::ServiceHandle
string Proxy.Proxy::__version__
string Proxy.Proxy::__verbs_supported
string Proxy.Proxy::__verbs_unsupported
string Proxy.Proxy::__verbs_safe
Proxy.Proxy::content
Proxy.Proxy::content_lenght
Proxy.Proxy::code
Proxy.Proxy::Allowed
Proxy.Proxy::parsed_path
Proxy.Proxy::proxy_user
Python 3 => removed self.headers.
>has_key<('Proxy-Authorization'): cambiado por 'in'
Proxy.Proxy::proxy_password
Proxy.Proxy::http_user
Python 3 => removed self.headers.
>has_key<('Authorization'): cambiado por 'in'
Proxy.Proxy::http_password
Proxy.Proxy::selfquery
TODO: aqui hay que cambiar que empiece por la cadena en vez de que sea la cadena TODO: cuando atacamos localhost:PUERTO (modo proxy), devuelve OK, pero cuando se ataca el servicio TODO: sin puerto, se devuelve como contenido las cabeceras.
Proxy.Proxy::what
Referenced by Proxy.Proxy.int_send_BODY.
Proxy.Proxy::client_headers
Proxy.Proxy::processed_headers
Proxy.Proxy::server_socket
Proxy.Proxy::server_wfile
def Proxy.Proxy.__init__
def Proxy.Proxy.log_message
def Proxy.Proxy.svc_hndl_FILE
References Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_BODY.
def Proxy.Proxy.svc_hndl_LIB
References Proxy.Proxy.bodySize, Proxy.Proxy.code, Proxy.Proxy.content_lenght, Proxy.Proxy.int_send_HEADERS_FILETYPE, Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_HEADERS.
def Proxy.Proxy.svc_hndl_ULIB
References Proxy.Proxy.bodySize, Proxy.Proxy.code, Proxy.Proxy.content_lenght, Proxy.Proxy.int_send_HEADERS_FILETYPE, Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_HEADERS.
def Proxy.Proxy.svc_hndl_DB
References Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_send_HEADERS_JSON, Proxy.Proxy.int_send_BODY.
def Proxy.Proxy.svc_hndl_VIRTUAL
References Proxy.Proxy.int_HEAD_PROXY_AUTH, Proxy.Proxy.int_HEAD_HTTP_AUTH, Proxy.Proxy.int_send_HEADERS_redirect.
def Proxy.Proxy.svc_hndl_CONFIG
References Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_HEADERS_redirect.
def Proxy.Proxy.svc_hndl_FAVICON
References Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_HEADERS_redirect.
def Proxy.Proxy.svc_hndl_STOP
References Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_send_BODY.
def Proxy.Proxy.svc_hndl_POST
References Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_send_BODY.
def Proxy.Proxy.svc_hndl_NOOP
References Proxy.Proxy.int_get_html_message, Proxy.Proxy.int_send_HEADERS, Proxy.Proxy.int_send_BODY.
def Proxy.Proxy.int_get_html_message
Referenced by Proxy.Proxy.svc_hndl_FILE, Proxy.Proxy.svc_hndl_LIB, Proxy.Proxy.svc_hndl_ULIB, Proxy.Proxy.svc_hndl_CONFIG, Proxy.Proxy.svc_hndl_FAVICON, Proxy.Proxy.svc_hndl_STOP, Proxy.Proxy.svc_hndl_NOOP.
def Proxy.Proxy.map_ext_to_filetype
Referenced by Proxy.Proxy.int_send_HEADERS_FILETYPE.
def Proxy.Proxy.int_send_HEADERS_JSON
References Proxy.Proxy.code, Proxy.Proxy.bodySize, Proxy.Proxy.content_lenght.
Referenced by Proxy.Proxy.svc_hndl_DB.
def Proxy.Proxy.int_send_HEADERS_redirect
References Proxy.Proxy.code.
Referenced by Proxy.Proxy.svc_hndl_VIRTUAL, Proxy.Proxy.svc_hndl_CONFIG, Proxy.Proxy.svc_hndl_FAVICON.
def Proxy.Proxy.int_send_HEADERS
References Proxy.Proxy.code, Proxy.Proxy.bodySize, Proxy.Proxy.content_lenght.
Referenced by Proxy.Proxy.svc_hndl_FILE, Proxy.Proxy.svc_hndl_LIB, Proxy.Proxy.svc_hndl_ULIB, Proxy.Proxy.svc_hndl_DB, Proxy.Proxy.svc_hndl_STOP, Proxy.Proxy.svc_hndl_POST, Proxy.Proxy.svc_hndl_NOOP.
def Proxy.Proxy.int_send_HEADERS_FILETYPE
References Proxy.Proxy.code, Proxy.Proxy.map_ext_to_filetype, Proxy.Proxy.bodySize.
Referenced by Proxy.Proxy.svc_hndl_LIB, Proxy.Proxy.svc_hndl_ULIB.
def Proxy.Proxy.int_send_BODY
References Proxy.Proxy.what, Cache.FileCache.path.
Referenced by Proxy.Proxy.svc_hndl_FILE, Proxy.Proxy.svc_hndl_DB, Proxy.Proxy.svc_hndl_STOP, Proxy.Proxy.svc_hndl_POST, Proxy.Proxy.svc_hndl_NOOP.
def Proxy.Proxy.int_HEAD_PROXY_AUTH
References Proxy.Proxy.code, Headers.ServerHeaders.server_version, Proxy.Proxy.server_version.
Referenced by Proxy.Proxy.svc_hndl_VIRTUAL.
def Proxy.Proxy.int_HEAD_HTTP_AUTH
References Proxy.Proxy.code, Headers.ServerHeaders.server_version, Proxy.Proxy.server_version.
Referenced by Proxy.Proxy.svc_hndl_VIRTUAL.
def Proxy.Proxy.parse_query
Referenced by Proxy.Proxy.do_CONNECT.
def Proxy.Proxy.handle_PROXY_AUTH
References Headers.ServerHeaders.headers.
def Proxy.Proxy.handle_HTTP_AUTH
References Headers.ServerHeaders.headers.
def Proxy.Proxy.BASIC
References Proxy.Proxy.content, Proxy.Proxy.content_lenght, Proxy.Proxy.code, Proxy.Proxy.processed_headers, Proxy.Proxy.content_cached, Proxy.Proxy.Allowed.
def Proxy.Proxy.do_CONNECT
References Proxy.Proxy.parse_query, Proxy.Proxy.parsed_path, Proxy.Proxy.Allowed, Proxy.Proxy.proxy_user, Proxy.Proxy.code, Proxy.Proxy.content_lenght, Cache.FileCache.path.