Cache::FileCache
string Cache.FileCache::path
Referenced by Proxy.Proxy.int_send_BODY, Proxy.Proxy.do_CONNECT.
string Cache.FileCache::md5hash_str
string Cache.FileCache::cache_filename_base
Referenced by Cache.FileCache.is_cached, Cache.FileCache.get.
string Cache.FileCache::cache_filename_meta
Referenced by Cache.FileCache.is_cached, Cache.FileCache.put.
string Cache.FileCache::cache_filename_cache
Referenced by Cache.FileCache.is_cached, Cache.FileCache.put, Cache.FileCache.get.
string Cache.FileCache::cache_filename_strip
string Cache.FileCache::cache_filename_header
Referenced by Cache.FileCache.put, Cache.FileCache.get.
Cache.FileCache::content_is_text
tuple Cache.FileCache::content_stripped
tuple Cache.FileCache::logger
Cache.FileCache::is_initialized
Referenced by Cache.FileCache.is_cached, Cache.FileCache.put, Cache.FileCache.get.
list Cache.FileCache::DEBUG
Referenced by Headers.ClientHeaders.parse, Headers.ServerHeaders.parsed_headers, Headers.ServerHeaders.dump.
Cache.FileCache::was_checked
Cache.FileCache::DEBUG
Referenced by Headers.ClientHeaders.parse, Headers.ServerHeaders.parsed_headers, Headers.ServerHeaders.dump.
Cache.FileCache::path
Referenced by Proxy.Proxy.int_send_BODY, Proxy.Proxy.do_CONNECT.
Cache.FileCache::md5hash
Cache.FileCache::cache_filename_base
Cache.FileCache::cache_filename_meta
Cache.FileCache::cache_filename_cache
Cache.FileCache::cache_filename_header
Cache.FileCache::cache_filename_strip
Cache.FileCache::content_stripped
def Cache.FileCache.remove_html_markup
def Cache.FileCache.__init__
def Cache.FileCache.setup
Referenced by Cache.FileCache.is_cached, Cache.FileCache.put, Cache.FileCache.get.
def Cache.FileCache.is_cached
References Cache.FileCache.is_initialized, Cache.FileCache.setup, Cache.FileCache.cache_filename_cache, Cache.FileCache.cache_filename_meta, Cache.FileCache.cache_filename_base.
def Cache.FileCache.put
References Cache.FileCache.is_initialized, Cache.FileCache.setup, Cache.FileCache.cache_filename_meta, Cache.FileCache.cache_filename_cache, Cache.FileCache.cache_filename_header.
def Cache.FileCache.get
References Cache.FileCache.is_initialized, Cache.FileCache.setup, Cache.FileCache.cache_filename_cache, Cache.FileCache.cache_filename_header, Cache.FileCache.cache_filename_base.