db_layer::Database
db_layer.Database::__initialized__
Referenced by db_layer.Database.__init__, db_log.Database.__init__.
db_layer.Database::__engine__
Referenced by db_layer.Database.__init__, db_log.Database.__init__.
db_layer.Database::__DBSession__
Referenced by db_layer.Database.__init__, db_layer.Database.findUser, db_layer.Database.findUserByUsername, db_layer.Database.isUserAllowed, db_layer.Database.isAdminAllowed, db_layer.Database.findUserByUID, db_layer.Database.getAllUser, db_layer.Database.getLowestUnusedUIDfromUser, db_layer.Database.addUser, db_layer.Database.addRelation, db_layer.Database.wr_addRelation, db_layer.Database.delRelation, db_layer.Database.wr_delRelation, db_layer.Database.delUser, db_layer.Database.setUserAdmin, db_layer.Database.changeUser, db_layer.Database.setUserAdvanced, db_layer.Database.setUserKid, db_layer.Database.setUserGuest, db_layer.Database.changeUserPassword, db_layer.Database.changeUserDescription, db_layer.Database.commitDBChanges, db_layer.Database.findGroup, db_layer.Database.findGroupByGroupname, db_layer.Database.findGroupByGID, db_layer.Database.delGroup, db_layer.Database.changeGroup, db_layer.Database.getAllGroups, db_layer.Database.getAllCustomGroups, db_layer.Database.getLowestUnusedGIDfromGroup, db_layer.Database.addGroup, db_layer.Database.changeGroupDescription, db_layer.Database.isUserAllowedNow, db_layer.Database.isUserAdmin, db_layer.Database.isUserAdvanced, db_layer.Database.isUserKid, db_layer.Database.isUserGuest, db_layer.Database.findGroupsByUser, db_layer.Database.findNotGroupsByUser, db_layer.Database.findURISbyGID, db_layer.Database.deleteURISbyGID, db_layer.Database.insertURISbyGID, db_layer.Database.wr_insertURISbyGID, db_layer.Database.findWORDSbyGID, db_layer.Database.deleteWORDSbyGID, db_layer.Database.insertWORDSbyGID, db_layer.Database.wr_insertWORDSbyGID, db_layer.Database.findMIMESbyGID, db_layer.Database.deleteMIMESbyGID, db_layer.Database.insertMIMESbyGID, db_layer.Database.wr_insertMIMESbyGID, db_layer.Database.getRULES, db_log.Database.__init__, db_log.Database.getLastLines, db_log.Database.addLine.
db_layer.Database::__BASE__
Referenced by db_layer.Database.__init__, db_log.Database.__init__.
db_layer.Database::session
Referenced by db_layer.Database.__init__, db_log.Database.__init__.
db_layer.Database::__metadata__
Referenced by db_layer.Database.__init__, db_log.Database.__init__.
def db_layer.Database.__init__
References db_layer.Database.__initialized__, db_layer.Database.__engine__, db_layer.Database.__metadata__, db_layer.Database.__BASE__, db_layer.Database.__DBSession__, db_layer.Database.session.
def db_layer.Database.findUser
References db_layer.Database.__DBSession__.
def db_layer.Database.findUserByUsername
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.isUserAllowed, db_layer.Database.isAdminAllowed, db_layer.Database.addUser, db_layer.Database.setUserAdmin, db_layer.Database.changeUser, db_layer.Database.setUserAdvanced, db_layer.Database.setUserKid, db_layer.Database.setUserGuest, db_layer.Database.changeUserPassword, db_layer.Database.changeUserDescription, db_layer.Database.isUserAllowedNow, db_layer.Database.isUserAdmin, db_layer.Database.isUserAdvanced, db_layer.Database.isUserKid, db_layer.Database.isUserGuest, db_layer.Database.findGroupsByUser, db_layer.Database.findNotGroupsByUser.
def db_layer.Database.isUserAllowed
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.isAdminAllowed
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername, db_layer.Database.isUserAdmin.
def db_layer.Database.findUserByUID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.addUser, db_layer.Database.addRelation, db_layer.Database.changeUser.
def db_layer.Database.getAllUser
References db_layer.Database.__DBSession__.
def db_layer.Database.getLowestUnusedUIDfromUser
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.addUser.
def db_layer.Database.addUser
References db_layer.Database.__DBSession__, db_layer.Database.getLowestUnusedUIDfromUser, db_layer.Database.findGroupByGID, db_layer.Database.findUserByUsername, db_layer.Database.findGroupByGroupname, db_layer.Database.findUserByUID.
def db_layer.Database.addRelation
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUID, db_layer.Database.findGroupByGID.
Referenced by db_layer.Database.wr_addRelation.
def db_layer.Database.wr_addRelation
References db_layer.Database.__DBSession__, db_layer.Database.addRelation.
def db_layer.Database.delRelation
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.wr_delRelation.
def db_layer.Database.wr_delRelation
References db_layer.Database.__DBSession__, db_layer.Database.delRelation.
def db_layer.Database.delUser
References db_layer.Database.__DBSession__.
def db_layer.Database.setUserAdmin
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.changeUser
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUID, db_layer.Database.findUserByUsername.
def db_layer.Database.setUserAdvanced
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.setUserKid
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.setUserGuest
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.changeUserPassword
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.changeUserDescription
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.commitDBChanges
References db_layer.Database.__DBSession__.
def db_layer.Database.findGroup
References db_layer.Database.__DBSession__.
def db_layer.Database.findGroupByGroupname
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.addUser, db_layer.Database.changeGroup, db_layer.Database.addGroup, db_layer.Database.changeGroupDescription.
def db_layer.Database.findGroupByGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.addUser, db_layer.Database.addRelation, db_layer.Database.changeGroup, db_layer.Database.addGroup, db_layer.Database.findGroupsByUser, db_layer.Database.findNotGroupsByUser.
def db_layer.Database.delGroup
References db_layer.Database.__DBSession__.
def db_layer.Database.changeGroup
References db_layer.Database.__DBSession__, db_layer.Database.findGroupByGID, db_layer.Database.findGroupByGroupname.
def db_layer.Database.getAllGroups
References db_layer.Database.__DBSession__.
def db_layer.Database.getAllCustomGroups
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.findNotGroupsByUser.
def db_layer.Database.getLowestUnusedGIDfromGroup
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.addGroup.
def db_layer.Database.addGroup
References db_layer.Database.__DBSession__, db_layer.Database.getLowestUnusedGIDfromGroup, db_layer.Database.findGroupByGroupname, db_layer.Database.findGroupByGID.
def db_layer.Database.changeGroupDescription
References db_layer.Database.__DBSession__, db_layer.Database.findGroupByGroupname.
def db_layer.Database.isUserAllowedNow
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.isUserAdmin
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
Referenced by db_layer.Database.isAdminAllowed.
def db_layer.Database.isUserAdvanced
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.isUserKid
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.isUserGuest
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername.
def db_layer.Database.findGroupsByUser
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername, db_layer.Database.findGroupByGID.
Referenced by db_layer.Database.findNotGroupsByUser.
def db_layer.Database.findNotGroupsByUser
References db_layer.Database.__DBSession__, db_layer.Database.findUserByUsername, db_layer.Database.getAllCustomGroups, db_layer.Database.findGroupsByUser, db_layer.Database.findGroupByGID.
def db_layer.Database.findURISbyGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.insertURISbyGID.
def db_layer.Database.deleteURISbyGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.insertURISbyGID.
def db_layer.Database.insertURISbyGID
References db_layer.Database.__DBSession__, db_layer.Database.deleteURISbyGID, db_layer.Database.findURISbyGID.
Referenced by db_layer.Database.wr_insertURISbyGID.
def db_layer.Database.wr_insertURISbyGID
References db_layer.Database.__DBSession__, db_layer.Database.insertURISbyGID.
def db_layer.Database.findWORDSbyGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.insertWORDSbyGID.
def db_layer.Database.deleteWORDSbyGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.insertWORDSbyGID.
def db_layer.Database.insertWORDSbyGID
References db_layer.Database.__DBSession__, db_layer.Database.deleteWORDSbyGID, db_layer.Database.findWORDSbyGID.
Referenced by db_layer.Database.wr_insertWORDSbyGID.
def db_layer.Database.wr_insertWORDSbyGID
References db_layer.Database.__DBSession__, db_layer.Database.insertWORDSbyGID.
def db_layer.Database.findMIMESbyGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.insertMIMESbyGID.
def db_layer.Database.deleteMIMESbyGID
References db_layer.Database.__DBSession__.
Referenced by db_layer.Database.insertMIMESbyGID.
def db_layer.Database.insertMIMESbyGID
References db_layer.Database.__DBSession__, db_layer.Database.deleteMIMESbyGID, db_layer.Database.findMIMESbyGID.
Referenced by db_layer.Database.wr_insertMIMESbyGID.
def db_layer.Database.wr_insertMIMESbyGID
References db_layer.Database.__DBSession__, db_layer.Database.insertMIMESbyGID.
def db_layer.Database.getRULES
References db_layer.Database.__DBSession__.