.TH "Cache.py" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBCache\&.FileCache\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCache\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBCache\&.remove_html_markup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCache\&.python_OldVersion\fP = True"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
