.TH "Cache" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBFileCache\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBremove_html_markup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpython_OldVersion\fP = True"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "def Cache\&.remove_html_markup (s)"

.PP
Definición en la línea 17 del archivo Cache\&.py\&.
.SH "Documentación de las variables"
.PP 
.SS "Cache\&.python_OldVersion = True"

.PP
Definición en la línea 6 del archivo Cache\&.py\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
