.TH "db_log.Database" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_log.Database \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBgetLastLines\fP"
.br
.ti -1c
.RI "def \fBaddLine\fP"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "\fBsession\fP = None"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 31 del archivo db_log\&.py\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "def db_log\&.Database\&.__init__ (self)"

.PP
Definición en la línea 37 del archivo db_log\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def db_log\&.Database\&.addLine (self, data)"

.PP
Definición en la línea 63 del archivo db_log\&.py\&.
.SS "def db_log\&.Database\&.getLastLines (self, numLines)"

.PP
Definición en la línea 53 del archivo db_log\&.py\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "db_log\&.Database\&.session = None\fC [static]\fP"

.PP
Definición en la línea 36 del archivo db_log\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
