.TH "db_layer.RolType" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_layer.RolType \- 
.SH SYNOPSIS
.br
.PP
.PP
Herencias object\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fBgetValue\fP"
.br
.ti -1c
.RI "def \fBgetKeys\fP"
.br
.ti -1c
.RI "def \fBgetValues\fP"
.br
.ti -1c
.RI "def \fBdbTypes\fP"
.br
.ti -1c
.RI "def \fBget_adm_user_key\fP"
.br
.ti -1c
.RI "def \fBget_adv_user_key\fP"
.br
.ti -1c
.RI "def \fBget_kid_user_key\fP"
.br
.ti -1c
.RI "def \fBget_guest_user_key\fP"
.br
.ti -1c
.RI "def \fBget_adm_user\fP"
.br
.ti -1c
.RI "def \fBget_adv_user\fP"
.br
.ti -1c
.RI "def \fBget_kid_user\fP"
.br
.ti -1c
.RI "def \fBget_guest_user\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 1016 del archivo db_layer\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def db_layer\&.RolType\&.dbTypes ()"

.PP
Definición en la línea 1023 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_adm_user ()"

.PP
Definición en la línea 1033 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_adm_user_key ()"

.PP
Definición en la línea 1025 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_adv_user ()"

.PP
Definición en la línea 1035 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_adv_user_key ()"

.PP
Definición en la línea 1027 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_guest_user ()"

.PP
Definición en la línea 1039 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_guest_user_key ()"

.PP
Definición en la línea 1031 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_kid_user ()"

.PP
Definición en la línea 1037 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.get_kid_user_key ()"

.PP
Definición en la línea 1029 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.getKeys ()"

.PP
Definición en la línea 1019 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.getValue (key)"

.PP
Definición en la línea 1017 del archivo db_layer\&.py\&.
.SS "def db_layer\&.RolType\&.getValues ()"

.PP
Definición en la línea 1021 del archivo db_layer\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
