.TH "db_layer.Rule" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_layer.Rule \- 
.SH SYNOPSIS
.br
.PP
.PP
Herencias object\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fBfromData\fP"
.br
.ti -1c
.RI "def \fB__repr__\fP"
.br
.ti -1c
.RI "def \fB__toString__\fP"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBuid\fP"
.br
.ti -1c
.RI "\fBgid\fP"
.br
.ti -1c
.RI "\fBusername\fP"
.br
.ti -1c
.RI "\fBgroupname\fP"
.br
.ti -1c
.RI "\fBtableid\fP"
.br
.ti -1c
.RI "\fBruleid\fP"
.br
.ti -1c
.RI "\fBrulecontent\fP"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "string \fBtableid\fP = ''"
.br
.ti -1c
.RI "int \fBruleid\fP = 0"
.br
.ti -1c
.RI "int \fBuid\fP = 0"
.br
.ti -1c
.RI "int \fBgid\fP = 0"
.br
.ti -1c
.RI "string \fBusername\fP = ''"
.br
.ti -1c
.RI "string \fBgroupname\fP = ''"
.br
.ti -1c
.RI "string \fBrulecontent\fP = ''"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 931 del archivo db_layer\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def db_layer\&.Rule\&.__repr__ (self)"

.PP
Definición en la línea 960 del archivo db_layer\&.py\&.
.SS "def db_layer\&.Rule\&.__toString__ (self)"

.PP
Definición en la línea 963 del archivo db_layer\&.py\&.
.SS "def db_layer\&.Rule\&.fromData (self, data)"

.PP
Definición en la línea 940 del archivo db_layer\&.py\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "int db_layer\&.Rule\&.gid = 0\fC [static]\fP"

.PP
Definición en la línea 935 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.gid"

.PP
Definición en la línea 943 del archivo db_layer\&.py\&.
.SS "string db_layer\&.Rule\&.groupname = ''\fC [static]\fP"

.PP
Definición en la línea 937 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.groupname"

.PP
Definición en la línea 945 del archivo db_layer\&.py\&.
.SS "string db_layer\&.Rule\&.rulecontent = ''\fC [static]\fP"

.PP
Definición en la línea 938 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.rulecontent"

.PP
Definición en la línea 949 del archivo db_layer\&.py\&.
.SS "int db_layer\&.Rule\&.ruleid = 0\fC [static]\fP"

.PP
Definición en la línea 933 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.ruleid"

.PP
Definición en la línea 948 del archivo db_layer\&.py\&.
.SS "string db_layer\&.Rule\&.tableid = ''\fC [static]\fP"

.PP
Definición en la línea 932 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.tableid"

.PP
Definición en la línea 947 del archivo db_layer\&.py\&.
.SS "int db_layer\&.Rule\&.uid = 0\fC [static]\fP"

.PP
Definición en la línea 934 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.uid"

.PP
Definición en la línea 942 del archivo db_layer\&.py\&.
.SS "string db_layer\&.Rule\&.username = ''\fC [static]\fP"

.PP
Definición en la línea 936 del archivo db_layer\&.py\&.
.SS "db_layer\&.Rule\&.username"

.PP
Definición en la línea 944 del archivo db_layer\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
