.TH "db_layer.AlchemyEncoder" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_layer.AlchemyEncoder \- 
.SH SYNOPSIS
.br
.PP
.PP
Herencias JSONEncoder\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fBdefault\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 80 del archivo db_layer\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def db_layer\&.AlchemyEncoder\&.default (self, obj)"

.PP
Definición en la línea 81 del archivo db_layer\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
