.TH "db_mapper" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_mapper \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBdb_handler\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBDEBUGCALL\fP = \fBConfig\&.DEBUG\fP['db_mapper\&.DEBUGCALL']"
.br
.ti -1c
.RI "list \fBDEBUGANSWER\fP = \fBConfig\&.DEBUG\fP['db_mapper\&.DEBUGANSWER']"
.br
.ti -1c
.RI "list \fBDEBUG\fP = Config\&.DEBUG['db_mapper\&.DEBUG']"
.br
.ti -1c
.RI "tuple \fBhandler\fP = \fBdb_handler\fP()"
.br
.ti -1c
.RI "tuple \fBanswer\fP = handler\&.handle_request(query='findUser', parms='username=%')"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "tuple db_mapper\&.answer = handler\&.handle_request(query='findUser', parms='username=%')"

.PP
Definición en la línea 226 del archivo db_mapper\&.py\&.
.SS "list db_mapper\&.DEBUG = Config\&.DEBUG['db_mapper\&.DEBUG']"

.PP
Definición en la línea 14 del archivo db_mapper\&.py\&.
.SS "list db_mapper\&.DEBUGANSWER = \fBConfig\&.DEBUG\fP['db_mapper\&.DEBUGANSWER']"

.PP
Definición en la línea 13 del archivo db_mapper\&.py\&.
.SS "list db_mapper\&.DEBUGCALL = \fBConfig\&.DEBUG\fP['db_mapper\&.DEBUGCALL']"

.PP
Definición en la línea 12 del archivo db_mapper\&.py\&.
.SS "tuple db_mapper\&.handler = \fBdb_handler\fP()"

.PP
Definición en la línea 225 del archivo db_mapper\&.py\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
