.TH "db_mapper.py" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_mapper.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBdb_mapper\&.db_handler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdb_mapper\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBdb_mapper\&.DEBUGCALL\fP = Config\&.DEBUG['db_mapper\&.DEBUGCALL']"
.br
.ti -1c
.RI "list \fBdb_mapper\&.DEBUGANSWER\fP = Config\&.DEBUG['db_mapper\&.DEBUGANSWER']"
.br
.ti -1c
.RI "list \fBdb_mapper\&.DEBUG\fP = Config\&.DEBUG['db_mapper\&.DEBUG']"
.br
.ti -1c
.RI "tuple \fBdb_mapper\&.handler\fP = db_handler()"
.br
.ti -1c
.RI "tuple \fBdb_mapper\&.answer\fP = handler\&.handle_request(query='findUser', parms='username=%')"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
