.TH "db_mapper.db_handler" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_mapper.db_handler \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBanswer_wrapper\fP"
.br
.ti -1c
.RI "def \fBmap_db2answer\fP"
.br
.ti -1c
.RI "def \fBhandle_request\fP"
.br
.ti -1c
.RI "def \fBmap_query2db\fP"
.br
.ti -1c
.RI "def \fBmap_parms2db\fP"
.br
.ti -1c
.RI "def \fBmap_dict2User\fP"
.br
.ti -1c
.RI "def \fBmap_dict2Group\fP"
.br
.ti -1c
.RI "def \fBmap_dict2URIS\fP"
.br
.ti -1c
.RI "def \fBmap_dict2WORDS\fP"
.br
.ti -1c
.RI "def \fBmap_dict2MIMES\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 17 del archivo db_mapper\&.py\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "def db_mapper\&.db_handler\&.__init__ (self)"

.PP
Definición en la línea 21 del archivo db_mapper\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def db_mapper\&.db_handler\&.answer_wrapper (self, to_type, answer)"

.PP
Definición en la línea 25 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.handle_request (self, query, parms)"

.PP
Definición en la línea 53 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_db2answer (self, query, answer)"

.PP
Definición en la línea 41 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_dict2Group (self, parms)"

.PP
Definición en la línea 151 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_dict2MIMES (self, parms)"

.PP
Definición en la línea 204 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_dict2URIS (self, parms)"

.PP
Definición en la línea 168 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_dict2User (self, parms)"

.PP
Definición en la línea 134 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_dict2WORDS (self, parms)"

.PP
Definición en la línea 187 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_parms2db (self, query, parms)"

.PP
Definición en la línea 105 del archivo db_mapper\&.py\&.
.SS "def db_mapper\&.db_handler\&.map_query2db (self, query)"

.PP
Definición en la línea 72 del archivo db_mapper\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
