.TH "Headers.ClientHeaders" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Headers.ClientHeaders \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBparse\fP"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBDEBUG\fP"
.br
.ti -1c
.RI "\fBip\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "list \fBDEBUG\fP = Config\&.DEBUG['ClientHeaders\&.DEBUG']"
.br
.ti -1c
.RI "string \fBip\fP = ''"
.br
.ti -1c
.RI "string \fBport\fP = ''"
.br
.ti -1c
.RI "tuple \fBlog\fP = \fBLog\fP()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 9 del archivo Headers\&.py\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "def Headers\&.ClientHeaders\&.__init__ (self, headers, debug = \fCFalse\fP, ip = \fC''\fP, port = \fC''\fP)"

.PP
Definición en la línea 19 del archivo Headers\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def Headers\&.ClientHeaders\&.parse (self)"

.PP
Definición en la línea 31 del archivo Headers\&.py\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "list Headers\&.ClientHeaders\&.DEBUG = Config\&.DEBUG['ClientHeaders\&.DEBUG']\fC [static]\fP"

.PP
Definición en la línea 10 del archivo Headers\&.py\&.
.SS "Headers\&.ClientHeaders\&.DEBUG"

.PP
Definición en la línea 23 del archivo Headers\&.py\&.
.SS "string Headers\&.ClientHeaders\&.ip = ''\fC [static]\fP"

.PP
Definición en la línea 14 del archivo Headers\&.py\&.
.SS "Headers\&.ClientHeaders\&.ip"

.PP
Definición en la línea 24 del archivo Headers\&.py\&.
.SS "tuple Headers\&.ClientHeaders\&.log = \fBLog\fP()\fC [static]\fP"

.PP
Definición en la línea 16 del archivo Headers\&.py\&.
.SS "string Headers\&.ClientHeaders\&.port = ''\fC [static]\fP"

.PP
Definición en la línea 15 del archivo Headers\&.py\&.
.SS "Headers\&.ClientHeaders\&.port"

.PP
Definición en la línea 25 del archivo Headers\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
