.TH "Log.py" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBLog\&.Log\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLog\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBLog\&.TRACE\fP = Config\&.TRACE['Log_TRACE']"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
