.TH "Log" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBLog\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBTRACE\fP = Config\&.TRACE['Log_TRACE']"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "list Log\&.TRACE = Config\&.TRACE['Log_TRACE']"

.PP
Definición en la línea 12 del archivo Log\&.py\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
