.TH "Log.Log" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log.Log \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBget_timestamp\fP"
.br
.ti -1c
.RI "def \fBpdebug\fP"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "\fBtheLOGDB\fP = None"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 15 del archivo Log\&.py\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "def Log\&.Log\&.__init__ (self)"

.PP
Definición en la línea 18 del archivo Log\&.py\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "def Log\&.Log\&.get_timestamp (self)"

.PP
Definición en la línea 21 del archivo Log\&.py\&.
.SS "def Log\&.Log\&.pdebug (self, args)"

.PP
Definición en la línea 24 del archivo Log\&.py\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "Log\&.Log\&.theLOGDB = None\fC [static]\fP"

.PP
Definición en la línea 16 del archivo Log\&.py\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
