.TH "main.py" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBmain\&.ThreadedServer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmain\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBmain\&.run\fP"
.br
.RI "\fIRun an HTTP server on port \fBConfig\&.PORT\fP\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmain\&.python_OldVersion\fP = True"
.br
.ti -1c
.RI "tuple \fBmain\&.logger\fP = Log()"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
