.TH "main" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBThreadedServer\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBrun\fP"
.br
.RI "\fIRun an HTTP server on port \fBConfig\&.PORT\fP\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpython_OldVersion\fP = True"
.br
.ti -1c
.RI "tuple \fBlogger\fP = \fBLog\fP()"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "def main\&.run (HandlerClass = \fCProxy\fP, ServerClass = \fCThreadedServer\fP, protocol = \fC'HTTP/1\&.0'\fP)"

.PP
Run an HTTP server on port \fBConfig\&.PORT\fP\&. 
.PP
Definición en la línea 37 del archivo main\&.py\&.
.SH "Documentación de las variables"
.PP 
.SS "tuple main\&.logger = \fBLog\fP()"

.PP
Definición en la línea 26 del archivo main\&.py\&.
.SS "main\&.python_OldVersion = True"

.PP
Definición en la línea 6 del archivo main\&.py\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
