.TH "Proxy" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proxy \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBProxy\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBdo_OPTIONS\fP"
.br
.RI "\fI__verbs_supported ='GET, HEAD, POST, PUT, TRACE, OPTIONS, CONNECT' xxx xxxx xxxx xxxxxxx xxxxxxx \fP"
.ti -1c
.RI "def \fBdo_HEAD\fP"
.br
.ti -1c
.RI "def \fBdo_TRACE\fP"
.br
.ti -1c
.RI "def \fBdo_GET\fP"
.br
.ti -1c
.RI "def \fBdo_POST\fP"
.br
.ti -1c
.RI "def \fBdo_OTHER\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpython_OldVersion\fP = True"
.br
.ti -1c
.RI "list \fBDEBUG\fP = Config\&.DEBUG['Proxy\&.DEBUG']"
.br
.ti -1c
.RI "list \fBDEBUG_BEFORE_HANDLING\fP = \fBConfig\&.DEBUG\fP['Proxy\&.DEBUG_BEFORE_HANDLING']"
.br
.ti -1c
.RI "\fBcontent\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "def Proxy\&.do_GET (self)"

.PP
Definición en la línea 1078 del archivo Proxy\&.py\&.
.SS "def Proxy\&.do_HEAD (self)"

.PP
Definición en la línea 1019 del archivo Proxy\&.py\&.
.SS "def Proxy\&.do_OPTIONS (self)"

.PP
__verbs_supported ='GET, HEAD, POST, PUT, TRACE, OPTIONS, CONNECT' xxx xxxx xxxx xxxxxxx xxxxxxx 
.PP
Definición en la línea 985 del archivo Proxy\&.py\&.
.SS "def Proxy\&.do_OTHER (self)"

.PP
Definición en la línea 1181 del archivo Proxy\&.py\&.
.SS "def Proxy\&.do_POST (self)"

.PP
Definición en la línea 1140 del archivo Proxy\&.py\&.
.SS "def Proxy\&.do_TRACE (self)"

.PP
Definición en la línea 1051 del archivo Proxy\&.py\&.
.SH "Documentación de las variables"
.PP 
.SS "Proxy\&.content"

.PP
Definición en la línea 986 del archivo Proxy\&.py\&.
.SS "list Proxy\&.DEBUG = Config\&.DEBUG['Proxy\&.DEBUG']"

.PP
Definición en la línea 31 del archivo Proxy\&.py\&.
.SS "list Proxy\&.DEBUG_BEFORE_HANDLING = \fBConfig\&.DEBUG\fP['Proxy\&.DEBUG_BEFORE_HANDLING']"

.PP
Definición en la línea 32 del archivo Proxy\&.py\&.
.SS "Proxy\&.path"

.PP
Definición en la línea 993 del archivo Proxy\&.py\&.
.SS "Proxy\&.python_OldVersion = True"

.PP
Definición en la línea 8 del archivo Proxy\&.py\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
