.TH "Proxy.py" 3 "Lunes, 30 de Diciembre de 2013" "Version 0.1" "Proxy doméstico con protección Parental" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proxy.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBProxy\&.Proxy\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProxy\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBProxy\&.do_OPTIONS\fP"
.br
.RI "\fI__verbs_supported ='GET, HEAD, POST, PUT, TRACE, OPTIONS, CONNECT' xxx xxxx xxxx xxxxxxx xxxxxxx \fP"
.ti -1c
.RI "def \fBProxy\&.do_HEAD\fP"
.br
.ti -1c
.RI "def \fBProxy\&.do_TRACE\fP"
.br
.ti -1c
.RI "def \fBProxy\&.do_GET\fP"
.br
.ti -1c
.RI "def \fBProxy\&.do_POST\fP"
.br
.ti -1c
.RI "def \fBProxy\&.do_OTHER\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBProxy\&.python_OldVersion\fP = True"
.br
.ti -1c
.RI "list \fBProxy\&.DEBUG\fP = Config\&.DEBUG['Proxy\&.DEBUG']"
.br
.ti -1c
.RI "list \fBProxy\&.DEBUG_BEFORE_HANDLING\fP = Config\&.DEBUG['Proxy\&.DEBUG_BEFORE_HANDLING']"
.br
.ti -1c
.RI "\fBProxy\&.content\fP"
.br
.ti -1c
.RI "\fBProxy\&.path\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Proxy doméstico con protección Parental del código fuente\&.
